main:
  - name: Bio
    url: /
    weight: 10

  - name: Blog
    url: https://sylvain.substack.com
    weight: 15
    params:
      newtab: true  # Ouvre Substack dans un nouvel onglet

  - name: Experience
    url: experience/
    weight: 20

  - name: Projects
    url: projects/
    weight: 30

  - name: Music
    url: music/
    weight: 40

  - name: Photo
    url: photo/
    weight: 50

  - name: Contact
    url: contact/
    weight: 60